name: Trigger AWS CodePipeline on Main Merge

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::046576049723:role/github-action-trigger-aws-pipeline
          aws-region: ap-southeast-2

      - name: Trigger CodePipeline
        run: |
          aws codepipeline start-pipeline-execution --name github-pipeline
